/* Renders whatever sits in a brand's drop folders.

   Reads content.json (regenerated by Editor_server.py on every request) and
   builds only the sections that actually have files. A brand with three films
   and nothing else renders films and nothing else - no empty headings.

   Used by index.html for the in-panel project view and by the standalone
   case-study pages under clients/<Brand>/.
*/
(function (root) {
  var cache = null;

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  /* Pages under clients/<Brand>/ sit two levels down, so paths need prefixing. */
  function depthPrefix() {
    return /\/clients\/[^/]+\//.test(location.pathname) ? '../../' : '';
  }
  function url(p) {
    return /^(https?:|data:|\/)/.test(p) ? p : depthPrefix() + p;
  }

  function load() {
    if (cache) return Promise.resolve(cache);
    return fetch(url('content.json') + '?t=' + Date.now())
      .then(function (r) { return r.ok ? r.json() : { brands: {} }; })
      .catch(function () { return { brands: {} }; })
      .then(function (d) { cache = d; return d; });
  }

  /* projects.json holds the campaign films (proj.vimeo). They were only ever
     shown in the edit-mode panel, so visitors never saw them. */
  var projectsCache = null;
  function loadProjects() {
    if (projectsCache) return Promise.resolve(projectsCache);
    return fetch(url('projects.json') + '?t=' + Date.now())
      .then(function (r) { return r.ok ? r.json() : {}; })
      .catch(function () { return {}; })
      .then(function (d) { projectsCache = d; return d; });
  }

  /* Films are hosted on Drive. Vimeo is deliberately not embeddable here: the
     account's videos required a sign-in, so the players showed a login wall. */
  function embedFor(source, id) {
    if (source === 'drive')   return 'https://drive.google.com/file/d/' + encodeURIComponent(id) + '/preview';
    if (source === 'youtube') return 'https://www.youtube.com/embed/' + encodeURIComponent(id);
    return '';
  }
  function watchFor(source, id) {
    if (source === 'drive')   return 'https://drive.google.com/file/d/' + encodeURIComponent(id) + '/view';
    if (source === 'youtube') return 'https://www.youtube.com/watch?v=' + encodeURIComponent(id);
    return '';
  }

  /* Anything named as a making-of goes in the second tab; everything else is
     the campaign itself. */
  var BTS_RE = /\b(bts|behind[\s_-]*the[\s_-]*scenes|behind[\s_-]*scenes|making[\s_-]*of|b-?roll)\b/i;
  function isBts(text) { return BTS_RE.test(String(text || '')); }

  /* Every film for a brand, from projects.json and from the drop folders. */
  function videosFor(slug) {
    return Promise.all([loadProjects(), load()]).then(function (res) {
      var store = res[0] || {}, dropped = res[1] || {};
      var out = [], seen = {};

      function add(title, source, id, watch) {
        if (!id || seen[source + ':' + id]) return;
        var embed = embedFor(source, id);
        if (!embed) return;                 // no player for this host, so skip it
        seen[source + ':' + id] = 1;
        out.push({ title: title || 'Film', embed: embed,
                   watch: watch || watchFor(source, id), bts: isBts(title) });
      }

      (((store[slug] || {}).projects) || []).forEach(function (p) {
        (p.vimeo || []).forEach(function (v) {
          if (v && v.id) add(v.label || p.name, v.source || 'vimeo', v.id);
        });
      });

      var entry = (dropped.brands || {})[slug] || {};
      (entry.links || []).forEach(function (l) {
        if (!l.embed || !l.id) return;
        add(l.title, l.provider, l.id, l.url);
      });
      (entry.videos || []).forEach(function (v) {
        if (seen['file:' + v.src]) return;
        seen['file:' + v.src] = 1;
        out.push({ title: v.title, file: url(v.src), bts: isBts(v.title || v.file) });
      });

      return out;
    });
  }

  function player(v) {
    var inner = v.file
      ? '<video src="' + esc(v.file) + '" controls preload="metadata" playsinline></video>'
      : '<iframe src="' + esc(v.embed) + '" title="' + esc(v.title) + '" loading="lazy" ' +
        'allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>';
    var cap = v.watch
      ? '<a href="' + esc(v.watch) + '" target="_blank" rel="noopener">' + esc(v.title) + ' ↗</a>'
      : esc(v.title);
    return '<figure class="pc-film">' + inner + '<figcaption>' + cap + '</figcaption></figure>';
  }

  function filmsSection(list) {
    if (!list.length) return '';
    var hero = list.filter(function (v) { return !v.bts; });
    var bts  = list.filter(function (v) { return v.bts; });
    if (!hero.length) { hero = bts; bts = []; }          // nothing but BTS: show it plainly

    var id = 'pcf' + Math.random().toString(36).slice(2, 8);
    var tabs = '', panes = '';
    if (bts.length) {
      tabs = '<div class="pc-tabs" role="tablist">' +
        '<button class="pc-tab on" data-pane="' + id + '-hero">The campaign (' + hero.length + ')</button>' +
        '<button class="pc-tab" data-pane="' + id + '-bts">Behind the scenes (' + bts.length + ')</button>' +
        '</div>';
      panes = '<div id="' + id + '-hero" class="pc-pane"><div class="pc-films">' + hero.map(player).join('') + '</div></div>' +
              '<div id="' + id + '-bts" class="pc-pane" hidden><div class="pc-films">' + bts.map(player).join('') + '</div></div>';
    } else {
      panes = '<div class="pc-pane"><div class="pc-films">' + hero.map(player).join('') + '</div></div>';
    }
    return section('Films', tabs + panes);
  }

  /* One delegated handler covers every tab set on the page. */
  document.addEventListener('click', function (e) {
    var tab = e.target.closest && e.target.closest('.pc-tab');
    if (!tab) return;
    var bar = tab.parentNode;
    Array.prototype.forEach.call(bar.children, function (b) { b.classList.toggle('on', b === tab); });
    var wrap = bar.parentNode;
    Array.prototype.forEach.call(bar.parentNode.querySelectorAll('.pc-pane'), function (p) {
      p.hidden = p.id !== tab.dataset.pane;
    });
  });

  function section(label, inner) {
    return '<section class="pc-section"><h3 class="pc-label">' + esc(label) + '</h3>' + inner + '</section>';
  }

  function images(list) {
    if (!list.length) return '';
    return section(list.length > 1 ? 'Visuals' : 'Visual',
      '<div class="pc-gallery">' + list.map(function (i) {
        return '<figure class="pc-shot">' +
          '<img src="' + esc(url(i.src)) + '" alt="' + esc(i.title) + '" loading="lazy">' +
          '</figure>';
      }).join('') + '</div>');
  }

  function videos(list) {
    if (!list.length) return '';
    return section(list.length > 1 ? 'Films' : 'Film',
      '<div class="pc-videos">' + list.map(function (v) {
        return '<figure class="pc-video">' +
          '<video src="' + esc(url(v.src)) + '" controls preload="metadata" playsinline></video>' +
          '<figcaption>' + esc(v.title) + '</figcaption>' +
          '</figure>';
      }).join('') + '</div>');
  }

  var DOC_ICON = { pdf: '▤', doc: '▤', docx: '▤', md: '✎', txt: '✎', rtf: '✎', odt: '✎' };

  function articles(list) {
    if (!list.length) return '';
    return section(list.length > 1 ? 'Writing' : 'Writing',
      '<ul class="pc-docs">' + list.map(function (a) {
        return '<li><a href="' + esc(url(a.src)) + '" target="_blank" rel="noopener">' +
          '<span class="pc-doc-ico">' + (DOC_ICON[a.ext] || '✎') + '</span>' +
          '<span class="pc-doc-name">' + esc(a.title) + '</span>' +
          '<span class="pc-doc-ext">' + esc(a.ext) + '</span></a></li>';
      }).join('') + '</ul>');
  }

  function links(list) {
    if (!list.length) return '';
    var embeds = list.filter(function (l) { return l.embed; });
    var plain = list.filter(function (l) { return !l.embed; });
    var html = '';

    if (embeds.length) {
      html += '<div class="pc-embeds">' + embeds.map(function (l) {
        return '<figure class="pc-embed pc-embed-' + esc(l.provider) + '">' +
          '<iframe src="' + esc(l.embed) + '" title="' + esc(l.title) + '" loading="lazy" ' +
          'allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>' +
          '<figcaption><a href="' + esc(l.url) + '" target="_blank" rel="noopener">' +
          esc(l.title) + ' ↗</a></figcaption>' +
          '</figure>';
      }).join('') + '</div>';
    }
    if (plain.length) {
      html += '<ul class="pc-links">' + plain.map(function (l) {
        return '<li><a href="' + esc(l.url) + '" target="_blank" rel="noopener">' +
          '<span class="pc-link-provider">' + esc(l.provider) + '</span>' +
          '<span class="pc-link-title">' + esc(l.title) + '</span> ↗</a></li>';
      }).join('') + '</ul>';
    }
    return section(embeds.length ? 'Decks & films' : 'Links', html);
  }

  /* Returns '' when the brand has nothing, so callers can skip the whole block. */
  function render(entry) {
    if (!entry) return '';
    return videos(entry.videos || []) +
           images(entry.images || []) +
           links(entry.links || []) +
           articles(entry.articles || []);
  }

  root.ProjectContent = {
    load: load,
    render: render,
    /* Films first, then whatever else the drop folders hold. */
    for: function (slug) {
      return Promise.all([load(), videosFor(slug)]).then(function (res) {
        var entry = (res[0].brands || {})[slug] || {};
        var films = filmsSection(res[1] || []);
        // Films are shown above, so drop the video files and the playable links
        // from the rest or each one appears twice on the page.
        var rest = render(Object.assign({}, entry, {
          videos: [],
          links: (entry.links || []).filter(function (l) { return !(l.embed && l.id); })
        }));
        return films + rest;
      });
    },
    has: function (slug) {
      return load().then(function (d) { return !!(d.brands || {})[slug]; });
    },
    // drop the cached content.json so the next call picks up newly added files
    refresh: function () { cache = null; }
  };
})(window);
