/* Renders whatever sits in a brand's drop folders, plus the films and decks
   recorded in projects.json.

   Reads content.json (regenerated by Editor_server.py on every request) and
   builds only the sections that actually have files. A brand with three films
   and nothing else renders films and nothing else - no empty headings.

   Used by index.html for the in-panel project view and by the standalone
   case-study pages under clients/<Brand>/.
*/
(function (root) {
  var cache = null;

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  /* Pages under clients/<Brand>/ sit two levels down, so paths need prefixing. */
  function depthPrefix() {
    return /\/clients\/[^/]+\//.test(location.pathname) ? '../../' : '';
  }
  function url(p) {
    return /^(https?:|data:|\/)/.test(p) ? p : depthPrefix() + p;
  }

  function load() {
    if (cache) return Promise.resolve(cache);
    return fetch(url('content.json') + (/^(localhost|127\.0\.0\.1)$/.test(location.hostname) ? '?t=' + Date.now() : ''))
      .then(function (r) { return r.ok ? r.json() : { brands: {} }; })
      .catch(function () { return { brands: {} }; })
      .then(function (d) { cache = d; return d; });
  }

  /* projects.json holds the campaign films and the decks (proj.vimeo, proj.media).
     They were only ever shown in the edit-mode panel, so visitors never saw them. */
  var projectsCache = null;
  function loadProjects() {
    if (projectsCache) return Promise.resolve(projectsCache);
    return fetch(url('projects.json') + (/^(localhost|127\.0\.0\.1)$/.test(location.hostname) ? '?t=' + Date.now() : ''))
      .then(function (r) { return r.ok ? r.json() : {}; })
      .catch(function () { return {}; })
      .then(function (d) { projectsCache = d; return d; });
  }

  /* campaigns.json: a short note and the target audience for each campaign,
     keyed by brand and then by the item's title. It fills in what links.txt
     leaves out, so a film without its own note still says what it was for. */
  var campaignsCache = null;
  function loadCampaigns() {
    if (campaignsCache) return Promise.resolve(campaignsCache);
    return fetch(url('campaigns.json') + (/^(localhost|127\.0\.0\.1)$/.test(location.hostname) ? '?t=' + Date.now() : ''))
      .then(function (r) { return r.ok ? r.json() : {}; })
      .catch(function () { return {}; })
      .then(function (d) { campaignsCache = d; return d; });
  }
  var KIND_KEY = { final: 'film', animatic: 'animatic', bts: 'bts' };
  function describe(c, item, kind) {
    var hit = (c.items || {})[item.title];
    var note = typeof hit === 'string' ? hit : hit && hit.note;
    if (!item.note) item.note = note || c[kind] || '';
    item.audience = (hit && typeof hit === 'object' && hit.audience) || c.audience || '';
  }

  /* Films are hosted on Drive. Vimeo is deliberately not embeddable here: the
     account's videos required a sign-in, so the players showed a login wall. */
  function embedFor(source, id) {
    if (source === 'drive')   return 'https://drive.google.com/file/d/' + encodeURIComponent(id) + '/preview';
    if (source === 'youtube') return 'https://www.youtube.com/embed/' + encodeURIComponent(id);
    return '';
  }
  function watchFor(source, id) {
    if (source === 'drive')   return 'https://drive.google.com/file/d/' + encodeURIComponent(id) + '/view';
    if (source === 'youtube') return 'https://www.youtube.com/watch?v=' + encodeURIComponent(id);
    return '';
  }

  /* Drive serves a still straight out at this address, no player around it, so
     a gallery can use it as a plain <img>. Stills stay on Drive with the films
     rather than being committed, which keeps the build small. */
  function driveImage(id) {
    return 'https://drive.google.com/thumbnail?id=' + encodeURIComponent(id) + '&sz=w1600';
  }

  /* Three kinds of film sit on a brand page and they are not the same work:
     the delivered ad, the animatic that sold it, and the shoot footage. A link
     says which it is through an [Animatic] or [BTS] tag on its title, which
     scan_content.py turns into .kind. Untagged films fall back to their name. */
  var ANIMATIC_RE = /\b(animatic|animatics|storyboard|story[\s_-]*board|concept[\s_-]*(cut|film|reel)?|rough[\s_-]*cut|boards)\b/i;
  var BTS_RE = /\b(bts|behind[\s_-]*the[\s_-]*scenes|behind[\s_-]*scenes|making[\s_-]*of|b-?roll)\b/i;

  function kindOf(tagged, text) {
    if (tagged === 'animatic' || tagged === 'bts' || tagged === 'final') return tagged;
    var s = String(text || '');
    if (BTS_RE.test(s)) return 'bts';
    if (ANIMATIC_RE.test(s)) return 'animatic';
    return 'final';
  }

  var KIND_LABEL = { final: 'Campaign', animatic: 'Animatic', bts: 'Behind the scenes' };
  var TAB_LABEL  = { final: 'The campaign', animatic: 'Animatics', bts: 'Behind the scenes' };

  /* Everything a brand has, gathered from projects.json and the drop folders.
     Returns films (playable), decks (Canva and the like) and shots (stills).

     opts.projectStills / opts.projectDecks turn off the projects.json side of
     the stills and the decks. The standalone brand page already builds those
     two from the same data in its own carousel, so it asks for films only;
     the home panel, which has no carousel, takes the lot. */
  function mediaFor(slug, opts) {
    opts = opts || {};
    var wantStills = opts.projectStills !== false;
    var wantDecks = opts.projectDecks !== false;
    return Promise.all([loadProjects(), load(), loadCampaigns()]).then(function (res) {
      var store = res[0] || {}, dropped = res[1] || {}, camp = (res[2] || {})[slug] || {};
      var films = [], decks = [], shots = [], seen = {};

      /* A social cut exported straight off a phone carries no usable name, so
         number it against the brand rather than leaving a row of "Film". */
      var brand = slug.replace(/-/g, ' ');
      var unnamed = 0;

      function addFilm(f, noteFn) {
        var key = f.embed || f.file;
        if (!key || seen[key]) return;   // a duplicate must not eat the note
        seen[key] = 1;
        f.kind = kindOf(f.kind, f.title);
        if (!f.title) f.title = brand + ', cut ' + (++unnamed);
        if (!f.note && noteFn) f.note = noteFn();
        films.push(f);
      }

      /* projects.json: campaign films, decks and stills, per project. */
      (((store[slug] || {}).projects) || []).forEach(function (p) {
        /* The project write-up belongs to the project, not to each of its
           cuts. It goes on the first film only; repeating it under all nine
           turned the panel into the same paragraph nine times. Per-film notes
           come from the third field in links.txt. */
        var pending = (p.desc || '').trim();
        function about() { var t = pending; pending = ''; return t; }

        (p.vimeo || []).forEach(function (v) {
          if (!v || !v.id) return;
          var embed = embedFor(v.source || 'vimeo', v.id);
          if (!embed) return;              // no player for this host, so skip it
          addFilm({ title: v.label || p.name, embed: embed,
                    watch: watchFor(v.source || 'vimeo', v.id) }, about);
        });
        (p.media || []).forEach(function (m) {
          if (!m) return;
          if (m.kind === 'drive' && m.id) {
            addFilm({ title: m.caption || m.label || p.name, embed: embedFor('drive', m.id),
                      watch: watchFor('drive', m.id) }, about);
          } else if (m.kind === 'youtube' && m.id) {
            addFilm({ title: m.caption || m.label || p.name, embed: embedFor('youtube', m.id),
                      watch: watchFor('youtube', m.id) }, about);
          } else if (m.kind === 'video' && m.src) {
            addFilm({ title: m.caption || m.label || p.name, file: url(m.src) }, about);
          } else if (m.kind === 'canva' && m.src && wantDecks) {
            decks.push({ title: m.label || m.caption || p.name, embed: m.src,
                         url: String(m.src).replace(/\?embed$/, ''), provider: 'canva', ratio: m.ratio });
          } else if (m.kind === 'img' && m.src && wantStills) {
            shots.push({ src: url(m.src), title: m.caption || m.label || p.name });
          }
        });
      });

      /* Drop folders: links.txt, .url shortcuts and dropped video files. */
      var entry = (dropped.brands || {})[slug] || {};
      (entry.links || []).forEach(function (l) {
        if (!l.embed || !l.id) return;
        if (l.kind === 'photo' && l.provider === 'drive') {
          // A still lives on Drive like everything else. Drive's file preview is
          // a player chrome, so point at the image itself instead.
          shots.push({ src: driveImage(l.id), title: l.title, href: l.url });
        } else if (l.provider === 'drive' || l.provider === 'youtube') {
          addFilm({ title: l.title, embed: l.embed, watch: l.url, note: l.note, kind: l.kind });
        } else {
          decks.push({ title: l.title, embed: l.embed, url: l.url,
                       provider: l.provider, note: l.note,
                       orient: l.orient, video: l.video, ratio: l.ratio });
        }
      });
      (entry.videos || []).forEach(function (v) {
        addFilm({ title: v.title, file: url(v.src), note: v.note });
      });

      /* Stills dropped in images/ come first; projects.json fills in behind. */
      shots = (entry.images || []).map(function (i) {
        return { src: url(i.src), title: i.title };
      }).concat(shots);

      var byShot = {};
      shots = shots.filter(function (s) {
        if (byShot[s.src]) return false;
        byShot[s.src] = 1;
        return true;
      });

      var byDeck = {};
      decks = decks.filter(function (d) {
        if (!d.embed || byDeck[d.embed]) return false;
        byDeck[d.embed] = 1;
        return true;
      });
      // films made in Canva open first, ahead of the decks
      decks = decks.filter(function (d) { return d.video; })
        .concat(decks.filter(function (d) { return !d.video; }));

      films.forEach(function (f) { describe(camp, f, KIND_KEY[f.kind] || 'film'); });
      decks.forEach(function (d) { describe(camp, d, d.video ? 'film' : 'deck'); });

      return { films: films, decks: decks, shots: shots };
    });
  }

  /* ---- the player -------------------------------------------------------
     One film plays at a time, with its note beside it and the rest of the set
     listed alongside, the way a video page reads. Showing every film at once
     turned a brand with twenty cuts into a wall of players nobody watched. */

  var STAGES = {};          // stage id -> the films it cycles through
  var uid = 0;
  function nextId() { return 'pcs' + (++uid); }

  function frameFor(v) {
    return v.file
      ? '<video src="' + esc(v.file) + '" controls preload="metadata" playsinline></video>'
      : '<iframe src="' + esc(v.embed) + '" title="' + esc(v.title) + '" loading="lazy" ' +
        'allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>';
  }

  function metaFor(v, i, total) {
    var bits = [KIND_LABEL[v.kind] || 'Film'];
    if (total > 1) bits.push((i + 1) + ' of ' + total);
    return '<p class="pc-now-kind">' + esc(bits.join(' · ')) + '</p>' +
      '<h4 class="pc-now-title">' + esc(v.title) + '</h4>' +
      (v.note ? '<p class="pc-now-note">' + esc(v.note) + '</p>' : '') +
      (v.audience ? '<p class="pc-aud"><b>Target audience</b>' + esc(v.audience) + '</p>' : '') +
      (v.watch ? '<a class="pc-now-open" href="' + esc(v.watch) + '" target="_blank" rel="noopener">Open the file ↗</a>' : '');
  }

  function stage(list) {
    if (!list.length) return '';
    var id = nextId();
    STAGES[id] = list;

    var rail = list.length < 2 ? '' :
      '<ol class="pc-rail" aria-label="More films">' + list.map(function (v, i) {
        return '<li><button type="button" class="pc-cue' + (i ? '' : ' on') + '" ' +
          'data-stage="' + id + '" data-i="' + i + '" aria-current="' + (i ? 'false' : 'true') + '">' +
          '<span class="pc-cue-n">' + (i + 1) + '</span>' +
          '<span class="pc-cue-body"><span class="pc-cue-title">' + esc(v.title) + '</span>' +
          '<span class="pc-cue-kind">' + esc(KIND_LABEL[v.kind] || 'Film') + '</span></span>' +
          '</button></li>';
      }).join('') + '</ol>';

    return '<div class="pc-stage' + (list.length < 2 ? ' pc-stage-solo' : '') + '" id="' + id + '">' +
      '<div class="pc-stage-main">' +
        '<div class="pc-frame">' + frameFor(list[0]) + '</div>' +
        '<div class="pc-now">' + metaFor(list[0], 0, list.length) + '</div>' +
      '</div>' + rail +
    '</div>';
  }

  /* One delegated handler covers every stage and every tab set on the page. */
  document.addEventListener('click', function (e) {
    if (!e.target.closest) return;

    // Full screen: the deck's own frame where the browser allows it, else the deck in a new tab.
    var fs = e.target.closest('.pc-fs');
    if (fs) {
      var frame = fs.closest('.pc-embed').querySelector('iframe');
      var go = frame && (frame.requestFullscreen || frame.webkitRequestFullscreen);
      if (go) {
        var p = go.call(frame);
        if (p && p.catch) p.catch(function () { window.open(fs.dataset.href, '_blank', 'noopener'); });
      } else {
        window.open(fs.dataset.href, '_blank', 'noopener');
      }
      return;
    }

    var cue = e.target.closest('.pc-cue');
    if (cue) {
      var wrap = document.getElementById(cue.dataset.stage);
      var list = STAGES[cue.dataset.stage];
      if (!wrap || !list) return;
      var i = +cue.dataset.i, v = list[i];
      if (!v) return;
      wrap.querySelector('.pc-frame').innerHTML = frameFor(v);
      wrap.querySelector('.pc-now').innerHTML = metaFor(v, i, list.length);
      Array.prototype.forEach.call(wrap.querySelectorAll('.pc-cue'), function (b) {
        var on = b === cue;
        b.classList.toggle('on', on);
        b.setAttribute('aria-current', on ? 'true' : 'false');
      });
      return;
    }

    var tab = e.target.closest('.pc-tab');
    if (!tab) return;
    var bar = tab.parentNode;
    Array.prototype.forEach.call(bar.children, function (b) {
      b.classList.toggle('on', b === tab);
      b.setAttribute('aria-selected', b === tab ? 'true' : 'false');
    });
    Array.prototype.forEach.call(bar.parentNode.querySelectorAll('.pc-pane'), function (p) {
      p.hidden = p.id !== tab.dataset.pane;
    });
  });

  /* Films split into the delivered work, the animatics and the shoot footage.
     One group means no tabs at all. */
  function filmsSection(list) {
    if (!list.length) return '';
    var groups = ['final', 'animatic', 'bts'].map(function (k) {
      return { kind: k, items: list.filter(function (v) { return v.kind === k; }) };
    }).filter(function (g) { return g.items.length; });

    if (groups.length === 1) return section('Films', stage(groups[0].items));

    var base = nextId();
    var tabs = '<div class="pc-tabs" role="tablist">' + groups.map(function (g, i) {
      return '<button type="button" class="pc-tab' + (i ? '' : ' on') + '" role="tab" ' +
        'aria-selected="' + (i ? 'false' : 'true') + '" data-pane="' + base + '-' + g.kind + '">' +
        esc(TAB_LABEL[g.kind]) + ' (' + g.items.length + ')</button>';
    }).join('') + '</div>';

    var panes = groups.map(function (g, i) {
      return '<div id="' + base + '-' + g.kind + '" class="pc-pane" role="tabpanel"' +
        (i ? ' hidden' : '') + '>' + stage(g.items) + '</div>';
    }).join('');

    return section('Films', tabs + panes);
  }

  function section(label, inner) {
    return '<section class="pc-section"><h3 class="pc-label">' + esc(label) + '</h3>' + inner + '</section>';
  }

  function images(list) {
    if (!list.length) return '';
    return section(list.length > 1 ? 'Visuals' : 'Visual',
      '<div class="pc-gallery">' + list.map(function (i) {
        var img = '<img src="' + esc(i.src) + '" alt="' + esc(i.title) + '" loading="lazy">';
        return '<figure class="pc-shot">' +
          (i.href ? '<a href="' + esc(i.href) + '" target="_blank" rel="noopener">' + img + '</a>' : img) +
          '</figure>';
      }).join('') + '</div>');
  }

  /* A deck is a whole presentation, so two of them stacked is a very long page.
     Past the first, each one gets its own tab and only the open one is built. */
  /* A reel made in Canva is 9:16, tagged [Reel] or [Vertical] in links.txt;
     it gets a phone-shaped frame instead of the 16:9 slide frame. */
  function deck(l) {
    return '<figure class="pc-embed pc-embed-' + esc(l.provider) +
      (l.orient === 'vertical' ? ' pc-embed-vertical' : '') + '"' +
      (/^\d+\/\d+$/.test(l.ratio || '') ? ' style="--r:' + l.ratio + '"' : '') + '>' +
      '<iframe src="' + esc(l.embed) + '" title="' + esc(l.title) + '" loading="lazy" ' +
      'allow="autoplay; fullscreen" allowfullscreen></iframe>' +
      '<figcaption>' +
      (l.note ? '<span class="pc-deck-note">' + esc(l.note) + '</span>' : '') +
      (l.audience ? '<span class="pc-aud"><b>Target audience</b>' + esc(l.audience) + '</span>' : '') +
      '<span class="pc-deck-actions"><button type="button" class="pc-fs" data-href="' + esc(l.url) + '">Full screen ⤢</button>' +
      '<a href="' + esc(l.url) + '" target="_blank" rel="noopener">' +
      esc(l.title) + ' ↗</a></span></figcaption>' +
      '</figure>';
  }

  /* Canva holds films as well as decks ([Reel] and [Video] in links.txt),
     so the heading says which this brand has. */
  function decksLabel(list) {
    var vids = list.filter(function (l) { return l.video; }).length;
    if (vids === list.length) return vids > 1 ? 'Videos' : 'Video';
    if (vids) return 'Decks and videos';
    return list.length > 1 ? 'Decks' : 'Deck';
  }

  function decksSection(list) {
    if (!list.length) return '';
    if (list.length === 1) return section(decksLabel(list), deck(list[0]));

    var base = nextId();
    var tabs = '<div class="pc-tabs" role="tablist">' + list.map(function (l, i) {
      return '<button type="button" class="pc-tab' + (i ? '' : ' on') + '" role="tab" ' +
        'aria-selected="' + (i ? 'false' : 'true') + '" data-pane="' + base + '-' + i + '">' +
        esc(l.title) + '</button>';
    }).join('') + '</div>';

    var panes = list.map(function (l, i) {
      return '<div id="' + base + '-' + i + '" class="pc-pane" role="tabpanel"' +
        (i ? ' hidden' : '') + '>' + deck(l) + '</div>';
    }).join('');

    return section(decksLabel(list), tabs + panes);
  }

  var DOC_ICON = { pdf: '▤', doc: '▤', docx: '▤', md: '✎', txt: '✎', rtf: '✎', odt: '✎' };

  function articles(list) {
    if (!list.length) return '';
    return section('Writing',
      '<ul class="pc-docs">' + list.map(function (a) {
        return '<li><a href="' + esc(url(a.src)) + '" target="_blank" rel="noopener">' +
          '<span class="pc-doc-ico">' + (DOC_ICON[a.ext] || '✎') + '</span>' +
          '<span class="pc-doc-name">' + esc(a.title) + '</span>' +
          '<span class="pc-doc-ext">' + esc(a.ext) + '</span></a></li>';
      }).join('') + '</ul>');
  }

  /* Links with no player of their own - Behance, Instagram, a plain page. */
  function links(list) {
    var plain = (list || []).filter(function (l) { return !l.embed; });
    if (!plain.length) return '';
    return section('Links',
      '<ul class="pc-links">' + plain.map(function (l) {
        return '<li><a href="' + esc(l.url) + '" target="_blank" rel="noopener">' +
          '<span class="pc-link-provider">' + esc(l.provider) + '</span>' +
          '<span class="pc-link-title">' + esc(l.title) + '</span> ↗</a></li>';
      }).join('') + '</ul>');
  }


  /* ---- the numbers -------------------------------------------------------
     charts.json holds what the strategy decks and the case form say in
     numbers: results against targets, audience splits, the plan in steps.
     Drawn here in the brand's colours with plain SVG and CSS. */
  var chartsCache = null;
  function loadCharts() {
    if (chartsCache) return Promise.resolve(chartsCache);
    return fetch(url('charts.json') + (/^(localhost|127\.0\.0\.1)$/.test(location.hostname) ? '?t=' + Date.now() : ''))
      .then(function (r) { return r.ok ? r.json() : {}; })
      .catch(function () { return {}; })
      .then(function (d) { chartsCache = d; return d; });
  }
  function fmtNum(n, unit) {
    if (unit === '%') return (Math.round(n * 100) / 100) + '%';
    if (n >= 1e6) return (Math.round(n / 1e5) / 10) + 'M';
    if (n >= 1e3) return (Math.round(n / 100) / 10) + 'K';
    return String(n);
  }
  function chartBars(c, col) {
    var max = 0;
    c.rows.forEach(function (r) { max = Math.max(max, r.result || 0, r.target || 0); });
    return '<div class="pc-bars">' + c.rows.map(function (r) {
      var w = max ? (r.result / max * 100) : 0, tw = r.target ? (r.target / max * 100) : 0;
      var beat = r.target ? r.result >= r.target : null;
      return '<div class="pc-bar"><div class="pc-bar-hd"><span>' + esc(r.label) + '</span><b>' + fmtNum(r.result, c.unit) +
        (r.target ? '<small> / ' + fmtNum(r.target, c.unit) + ' target</small>' : '') + '</b></div>' +
        '<div class="pc-bar-track"><i style="width:' + w.toFixed(1) + '%;background:' + (beat === false ? col[1] || '#888' : col[0]) + '"></i>' +
        (r.target ? '<em style="left:' + tw.toFixed(1) + '%" title="Target"></em>' : '') + '</div></div>';
    }).join('') + '</div>' +
    (c.rows.some(function (r) { return r.target; }) ? '<p class="pc-chart-key"><i style="background:' + col[0] + '"></i>Result <em></em>Target</p>' : '');
  }
  function chartPie(c, col) {
    var total = c.data.reduce(function (s, d) { return s + d[1]; }, 0) || 1, a = -Math.PI / 2, R = 42, r = 26;
    var pal = col.concat(['#f0c233', '#8b5cf6', '#2ecc71', '#e67e22', '#95a5a6']);
    var segs = c.data.map(function (d, i) {
      var f = d[1] / total, a2 = a + f * Math.PI * 2, big = f > 0.5 ? 1 : 0;
      var p = function (rad, ang) { return (50 + rad * Math.cos(ang)).toFixed(2) + ' ' + (50 + rad * Math.sin(ang)).toFixed(2); };
      var path = f >= 0.9999
        ? '<circle cx="50" cy="50" r="' + ((R + r) / 2) + '" fill="none" stroke="' + pal[i] + '" stroke-width="' + (R - r) + '"/>'
        : '<path d="M' + p(R, a) + ' A' + R + ' ' + R + ' 0 ' + big + ' 1 ' + p(R, a2) + ' L' + p(r, a2) + ' A' + r + ' ' + r + ' 0 ' + big + ' 0 ' + p(r, a) + 'Z" fill="' + pal[i] + '"/>';
      a = a2; return path;
    }).join('');
    return '<div class="pc-pie"><svg viewBox="0 0 100 100" role="img" aria-label="' + esc(c.title) + '">' + segs + '</svg><ul>' +
      c.data.map(function (d, i) {
        return '<li><i style="background:' + pal[i] + '"></i>' + esc(d[0]) + '<b>' + (c.unit === '%' ? fmtNum(d[1], '%') : Math.round(d[1] / total * 100) + '%') + '</b></li>';
      }).join('') + '</ul></div>';
  }
  function chartTiles(c, col) {
    return '<div class="pc-tiles">' + c.data.map(function (d) {
      return '<div class="pc-tile" style="border-color:' + col[0] + '"><b style="color:' + col[0] + '">' + esc(d[1]) + '</b><span>' + esc(d[0]) + '</span></div>';
    }).join('') + '</div>';
  }
  function chartTimeline(c, col) {
    return '<ol class="pc-steps">' + c.steps.map(function (s, i) {
      return '<li><span class="pc-step-dot" style="background:' + col[i % col.length] + '">' + (i + 1) + '</span><b>' + esc(s[0]) + '</b><span>' + esc(s[1]) + '</span></li>';
    }).join('') + '</ol>';
  }
  var CHART = { bars: chartBars, pie: chartPie, tiles: chartTiles, timeline: chartTimeline };
  // a brand colour too dark to read on the page gives way to the next one
  function readable(spec) {
    var col = ((spec && spec.colors) || ['#f0c233']).filter(function (h) {
      var m = /^#?([0-9a-f]{6})$/i.exec(h); if (!m) return true;
      var n = parseInt(m[1], 16), l = 0.299 * (n >> 16) + 0.587 * (n >> 8 & 255) + 0.114 * (n & 255);
      return l > 45;
    });
    return col.length ? col : ['#f0c233', '#8b5cf6'];
  }
  /* The headline results: the strongest numbers, shown big under the page's hero. */
  function resultsStrip(spec) {
    if (!spec || !spec.headline || !spec.headline.length) return '';
    var col = spec.colors ? readable(spec)[0] : 'var(--accent,#f0c233)';
    return '<div class="pc-results">' + spec.headline.map(function (d) {
      return '<div class="pc-result"><b style="color:' + col + '">' + esc(d[0]) + '</b><span>' + esc(d[1]) + '</span></div>';
    }).join('') + '</div>' + (spec.source ? '<p class="pc-chart-src">Source: ' + esc(spec.source) + '</p>' : '');
  }
  function chartsSection(spec) {
    if (!spec || !spec.charts || !spec.charts.length) return '';
    var col = readable(spec);
    return section('The numbers', '<div class="pc-charts">' + spec.charts.map(function (c) {
      var draw = CHART[c.type]; if (!draw) return '';
      return '<figure class="pc-chart pc-chart-' + c.type + '"><figcaption>' + esc(c.title) + '</figcaption>' + draw(c, col) + '</figure>';
    }).join('') + '</div>' + (spec.source ? '<p class="pc-chart-src">Source: ' + esc(spec.source) + '</p>' : ''));
  }

  /* Kept for callers that hand over a raw content.json entry. */
  function render(entry) {
    if (!entry) return '';
    return images((entry.images || []).map(function (i) {
             return { src: url(i.src), title: i.title };
           })) +
           links(entry.links || []) +
           articles(entry.articles || []);
  }

  root.ProjectContent = {
    load: load,
    render: render,
    /* Films first, then decks, stills and writing. */
    for: function (slug, opts) {
      return Promise.all([load(), mediaFor(slug, opts), loadCharts()]).then(function (res) {
        var entry = (res[0].brands || {})[slug] || {};
        var m = res[1];
        return chartsSection((res[2] || {})[slug]) +
               filmsSection(m.films) +
               decksSection(m.decks) +
               images(m.shots) +
               links(entry.links || []) +
               articles(entry.articles || []);
      });
    },
    results: function (slug) {
      return loadCharts().then(function (d) { return resultsStrip((d || {})[slug]); });
    },
    has: function (slug) {
      return Promise.all([load(), loadProjects(), loadCharts()]).then(function (res) {
        return !!((res[0].brands || {})[slug] || (res[1] || {})[slug] || (res[2] || {})[slug]);
      });
    },
    // drop the cached content.json so the next call picks up newly added files
    refresh: function () { cache = null; projectsCache = null; chartsCache = null; campaignsCache = null; }
  };
})(window);
