/* Shared brand → industry map. Used by clients.html (grouping) and projects.js
   (prefills the Brand Profile template). Edit a brand's industry here, or in edit mode. */
(function(){
  // Canonical industry order shown on the registry
  window.INDUSTRY_ORDER = [
    'Automotive',
    'Food & Beverage',
    'FMCG',
    'Fashion & Apparel',
    'Beauty & Personal Care',
    'Hospitality & Real Estate',
    'Home & Living',
    'Tech & Telecom',
    'Media & Entertainment',
    'Banking & Finance',
    'Healthcare',
    'Web Design & Copywriting',
    'Other / Agency'
  ];
  window.BRAND_INDUSTRY = {
    'Geely':'Automotive',
    'Audi':'Automotive',
    'Subway-Oman':'Food & Beverage',
    'Hardees':'Food & Beverage',
    'GDK':'Food & Beverage',
    'Lord-of-the-Wings':'Food & Beverage',
    'Gourmet':'FMCG',
    'Krispy-Kreme':'Food & Beverage',
    'Brew-Craft':'Food & Beverage',
    'Noodle-House':'Food & Beverage',
    'Burger-Pump':'Food & Beverage',
    'Zooba':'Food & Beverage',
    'Em-Sherif-Cafe':'Food & Beverage',
    'Emirgan-Sutis':'Food & Beverage',
    'Chouchou':'Food & Beverage',
    'Defarm':'FMCG',
    'Lifebox':'Food & Beverage',
    'Nineteen84':'Other / Agency',
    'Bazooka-Candy':'FMCG',
    'Molfix':'FMCG',
    'Juicy-Drop':'FMCG',
    'Big-Baby-Pop':'FMCG',
    'Ring-Pop':'FMCG',
    'Bonny':'FMCG',
    'Hayat-Water':'FMCG',
    'Steam-Cola':'FMCG',
    'Carina':'FMCG',
    'Royal-Herbs':'FMCG',
    'Delight-Pastries':'Food & Beverage',
    'Bohobun':'Food & Beverage',
    'Kappa':'Fashion & Apparel',
    'Bershka':'Fashion & Apparel',
    'Polo-Ralph-Lauren':'Fashion & Apparel',
    'Mostique':'Fashion & Apparel',
    'MTM':'Fashion & Apparel',
    'Biella':'Food & Beverage',
    'Glow':'FMCG',
    'Revitalash':'Beauty & Personal Care',
    'Gillette-Venus':'Beauty & Personal Care',
    'AXE-Unilever':'Beauty & Personal Care',
    'Royal-Tulip-Hotel':'Hospitality & Real Estate',
    'Memaar-Al-Morshedy':'Hospitality & Real Estate',
    'Deraya-Real-Estate':'Hospitality & Real Estate',
    'Almaza-Bay':'Hospitality & Real Estate',
    'El-Gouna':'Hospitality & Real Estate',
    'One-Zaabeel':'Hospitality & Real Estate',
    'The-G-Hotels':'Hospitality & Real Estate',
    'The-Center':'Other / Agency',
    'Medina':'Hospitality & Real Estate',
    'ACUD':'Hospitality & Real Estate',
    'No-Limits-Furniture':'Home & Living',
    'Quooker':'Home & Living',

    'Snapchat':'Tech & Telecom',
    'Aevapay':'Tech & Telecom',
    'Fujifilm':'Tech & Telecom',
    'WallPost':'Web Design & Copywriting',
    'EA-FC-Mobile':'Media & Entertainment',
    'Delight-Parties':'Food & Beverage',
    'Imagine-Studio':'Media & Entertainment',
    'URBEELS':'Media & Entertainment',
    'Bibliotheca-Alexandrina':'Media & Entertainment',
    'Warba-Bank':'Banking & Finance',

    'Deraya':'Banking & Finance',
    'Mayo-Clinic':'Healthcare',
    'The-Recovery-Clinic':'Healthcare',
    'Tonic-International':'Other / Agency',
    'Al-Siddiqi-Holding':'Web Design & Copywriting',
    'Mansour':'Other / Agency',
    'CAPA':'Other / Agency',
    'Escapegoat-Sound':'Media & Entertainment',
    'Labanita':'FMCG',
    'BIC-WNA':'FMCG',
    'Eldib-Co':'Web Design & Copywriting',
    'Blue-Ocean-Sharm':'Web Design & Copywriting',
    'Carzami':'Web Design & Copywriting'
  };
})();
